language: rust

before_script:
- cargo install --force rustfmt-nightly && rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
- which rustfmt
- rustfmt --version
script:
- cargo fmt -- --write-mode=diff
- cargo test --verbose
